package com.sh.entity;
// Generated 2016-10-2 12:05:54 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * BuyPrice generated by hbm2java
 */
@Entity
@Table(name = "buy_price", catalog = "xcxt")
@DynamicInsert(true)
@DynamicUpdate(true)
public class BuyPrice implements java.io.Serializable {

	private Integer id;
	private Integer foodId;
	private String foodName;
	private Integer foodCategory;
	private Double price;
	private Date buyDate;
	private Integer isDefault;

	public BuyPrice() {
	}

	public BuyPrice(String foodName, Integer foodId, Integer foodCategory, Double price, Date buyDate, Integer isDefault) {
		this.foodId = foodId;
		this.foodName = foodName;
		this.foodCategory = foodCategory;
		this.price = price;
		this.buyDate = buyDate;
		this.isDefault = isDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "food_id", columnDefinition="int default 0")
	public Integer getFoodId() {
		return foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "food_name", length = 50)
	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	@Column(name = "food_category",columnDefinition="int default 0")
	public Integer getFoodCategory() {
		return this.foodCategory;
	}

	public void setFoodCategory(Integer foodCategory) {
		this.foodCategory = foodCategory;
	}

	@Column(name = "price", precision = 22, scale = 0,columnDefinition="double default 0")
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "buy_date", length = 10)
	public Date getBuyDate() {
		return this.buyDate;
	}

	public void setBuyDate(Date buyDate) {
		this.buyDate = buyDate;
	}

	@Column(name = "is_default",columnDefinition="int default 0")
	public Integer getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

}
