package com.sh.entity;
// Generated 2016-9-21 21:18:40 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", catalog = "xcxt")
public class Menu implements java.io.Serializable {

	private Integer id;
	private Date createTime;
	private Integer listno;
	private String name;
	private Integer parentId;
	private String url;

	public Menu() {
	}

	public Menu(Date createTime, Integer listno, String name, Integer parentId, String url) {
		this.createTime = createTime;
		this.listno = listno;
		this.name = name;
		this.parentId = parentId;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "listno", columnDefinition="INT default 0")
	public Integer getListno() {
		return this.listno;
	}

	public void setListno(Integer listno) {
		this.listno = listno;
	}

	@Column(name = "name", length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "parent_id", columnDefinition="INT default 0")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "url", length = 128)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
