package com.sh.entity;
// Generated 2016-9-21 21:18:40 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RolePerm generated by hbm2java
 */
@Entity
@Table(name = "role_perm", catalog = "xcxt")
public class RolePerm implements java.io.Serializable {

	private Integer id;
	private Integer menuId;
	private Integer roleId;

	public RolePerm() {
	}

	public RolePerm(Integer menuId, Integer roleId) {
		this.menuId = menuId;
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "menu_id")
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "role_id")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

}
